import type { CategoryId } from '@/types';

// Prompt templates for each category
// {brand} will be replaced at query time if needed
const PROMPT_TEMPLATES: Record<CategoryId, string[]> = {
  beauty: [
    'best natural face wash in India',
    'top skincare brands in India 2025',
    'best moisturizer for Indian skin',
    'recommended sunscreen brands India',
    'best anti-aging cream India',
    'top 10 beauty brands in India',
    'best face serum for glowing skin India',
    'organic skincare brands India',
    'which is the best Indian skincare brand',
    'best lip balm brands India',
    'affordable skincare routine India',
    'best coffee face wash India',
    'best vitamin C serum India',
    'cruelty free beauty brands India',
    'best D2C beauty brands India',
  ],
  food: [
    'best online meat delivery India',
    'top D2C food brands India',
    'best organic tea brands India',
    'best milk delivery service India',
    'healthy snack brands India',
    'best protein bar brands India',
    'best cold pressed juice India',
    'organic food brands India online',
    'best Indian coffee brands online',
    'best muesli brands India',
    'plant based food brands India',
    'best ghee brands India online',
    'best spice brands India D2C',
    'top food startups India',
    'best subscription food boxes India',
  ],
  health: [
    'best protein powder India',
    'top health supplement brands India',
    'best collagen supplement India',
    'best multivitamin for Indian men',
    'best plant based protein India',
    'top wellness brands India',
    'best ashwagandha supplement India',
    'best biotin supplement India',
    'recommended health drinks India',
    'best omega 3 supplement India',
    'best weight loss supplement India',
    'ayurvedic supplement brands India',
    'best pre workout supplement India',
    'top D2C health brands India',
    'best gut health supplement India',
  ],
  fashion: [
    'best online fashion brands India',
    'top D2C fashion brands India',
    'best t-shirt brands India online',
    'affordable streetwear brands India',
    'best mens fashion brands India D2C',
    'best graphic tee brands India',
    'sustainable fashion brands India',
    'best denim brands India online',
    'best athleisure brands India',
    'top Indian clothing brands for men',
    'best oversized t-shirt brands India',
    'affordable fashion startups India',
    'best sneaker brands India',
    'best Indian ethnic wear brands online',
    'best casual wear brands India',
  ],
  electronics: [
    'best wireless earbuds India',
    'top smartwatch brands India under 5000',
    'best bluetooth speakers India',
    'best TWS earbuds India 2025',
    'top Indian electronics brands',
    'best neckband earphones India',
    'best smart band India',
    'best portable charger India',
    'best gaming headphones India',
    'budget smartwatch brands India',
    'best Indian audio brands',
    'best wireless headphones India',
    'best earbuds under 2000 India',
    'top D2C electronics brands India',
    'best noise cancelling earbuds India',
  ],
  baby: [
    'best baby care brands India',
    'top baby skincare brands India',
    'best diaper brands India',
    'best baby shampoo India',
    'safest baby products India',
    'organic baby care brands India',
    'best baby lotion India',
    'best baby food brands India',
    'recommended baby products Indian parents',
    'best baby cream for Indian skin',
    'best newborn care products India',
    'top D2C baby brands India',
    'best baby sunscreen India',
    'best baby oil brands India',
    'best baby toys brands India online',
  ],
  home: [
    'best mattress brands India online',
    'best pillow brands India',
    'top D2C home decor brands India',
    'best bed sheets brands India online',
    'best mattress for back pain India',
    'best furniture brands India online',
    'best sleep products India',
    'best orthopedic mattress India',
    'best duvet brands India',
    'best memory foam mattress India',
    'best home fragrance brands India',
    'best towel brands India online',
    'best curtain brands India online',
    'top home and living startups India',
    'best smart home products India',
  ],
  pet: [
    'best dog food brands India',
    'top pet care brands India',
    'best cat food India',
    'best pet store online India',
    'best dog treats India',
    'recommended pet supplements India',
    'best pet grooming products India',
    'best puppy food India',
    'best pet accessories online India',
    'best grain free dog food India',
    'top D2C pet brands India',
    'best pet shampoo India',
    'best pet toys online India',
    'best pet food delivery India',
    'best cat litter brands India',
  ],
};

export function getPromptsForCategory(category: CategoryId): string[] {
  return PROMPT_TEMPLATES[category] || PROMPT_TEMPLATES.beauty;
}

export function getAllCategories(): CategoryId[] {
  return Object.keys(PROMPT_TEMPLATES) as CategoryId[];
}
